services:
  qdrant:
    image: qdrant/qdrant
    ports: ["6333:6333"]
    volumes: ["./data/qdrant:/qdrant/storage"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: videorag
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d videorag"] 
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    volumes: ["./data/minio:/data"]

  model-downloader:
    image: alpine/curl
    volumes:
      - ./models:/models
    # Usamos '|' para mantener los saltos de línea en el script
    command: >
      sh -c "
        apk add --no-cache curl &&
        if [ ! -f /models/llama-3.2-1b-instruct-q4_k_m.gguf ]; then
          echo 'Model not found, downloading...' &&
          curl -L -o /models/llama-3.2-1b-instruct-q4_k_m.gguf https://huggingface.co/Fetuffo78/Llama-3.2-1B-Instruct-Q4_K_M-GGUF/resolve/main/llama-3.2-1b-instruct-q4_k_m.gguf &&
          echo 'Download complete.'
        else
          echo 'Model already exists, skipping download.'
        fi
      "

  transcription:
    build: ./src/transcription
    ports: ["8001:8001"]
    volumes:
      - ./src/transcription:/app/transcription
      - whisper-cache:/root/.cache/whisper
      - ./models:/models
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: videorag
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      HF_TOKEN: ${HF_TOKEN}
    # Obligamos a que espere a que la descarga termine completamente
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      model-downloader:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build: ./src/frontend
    ports: ["8501:8501"]
    volumes:
      - ./src/frontend:/app
    environment:
      API_URL: http://transcription:8001
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_EXTERNAL_URL: http://localhost:9000
    depends_on:
      transcription:
        condition: service_healthy # ← espera al healthcheck

volumes:
  whisper-cache: